services:
  app:
    build: 
      target: prod
      context: .
    restart: never
    image: cheese-vault
    env_file:
      - ${ENV_FILE_PATH}
    volumes:
      - ${LOCAL_DB_PATH}:/usr/src/app/local.db:Z