services:
  app:
    build: .
    restart: always
    image: cheese-vault
    env_file:
      - /home/herobread/actions-runner/env-vars/.env
    ports:
      - "3000:3000"
    volumes:
      - /home/herobread/actions-runner/data/local.db:/usr/src/app/local.db