name: Deploy Bot

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout latest code
              uses: actions/checkout@v4

            - name: Stop old containers
              run: docker compose down

            - name: Build and restart docker-compose
              run: docker compose up -d --build
